<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ltube_toolbox"
 *
 * Auto generated by Extension Builder 2016-03-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Learntube Toolbox',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Pranab Ojha',
	'author_email' => 'pojha@learntube.in',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
    'autoload' => array(
        'classmap' => array('Classes')
    ),
);